services:
  db:
    image: postgres:15
    container_name: docker_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: docker_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    restart: always
